show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
author: jeetprksh
twitter:
  username: jeetprksh
  card: summary
social:
  name: Jeet Prakash
  links:
    - https://twitter.com/jeetprksh
    - https://www.linkedin.com/in/jeetprakash
    - https://github.com/jeetprksh